write ("Welcome to the Leauge of Asterix, type y to continue !")
let confirmation = input()
IF confirmation == "y" THEN let level1 = " Do you know the real name of asterix (just first name)?" ELSE let level1 = " GAME OVER !!"
write (level1)
let name = input()
IF name == "sgl" THEN let level2 = " right that's what her real name you might be someone from L-5 (the group of 5 legends ) if you are tell me because who india gots its independence (just tell me his surname cuz he is so popular in the just because of his high-score which is 6 millions) " ELSE let level2 = "GAME OVER YOU LOST NIGGER"
write (level2)
let legend = input()
IF legend == "hitler" THEN let level3 = "right that painter was legend btw for his cause \o " ELSE let level3 = "game over nerd "
write (level3)
write ("you have won this successfully!")